import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/ui/main-header";
import MainFooter from "@/components/ui/main-footer";
import { SessionProvider } from "next-auth/react";
import { Provider } from "react-redux";
import { store } from "./store";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Provider store={store}>
                    <SessionProvider>
                        <MainHeader />
                        <main className="flex flex-col items-center py-16">
                            {children}
                        </main>
                        <MainFooter />
                    </SessionProvider>
                </Provider>
            </body>
        </html>
    );
}
